### ISSUE TITLE
pipenv suport

### ISSUE THREAD

**Issue by leiserfg** [pythonic-emacs/anaconda-mode#283]
Detect pipenv and use it for virtualenv.

**Comment by proofit404** [comment]
Looks like a ticket from the customer...

**Comment by valignatev** [comment]
@leiserfg There is a [pipenv.el](https://github.com/pwalsh/pipenv.el), which works in a way that anaconda-mode understands. At least intellisense features of anaconda-mode work for me, have you tried it out?

**Comment by ahonnecke** [comment]
@valignatev I had pipenv and anaconda mode working together at some point, but whatever I have set up seems to be fairly brittle.  Can you recommend documentation for troubleshooting or steps that I might be able to take to look into why completion is not working?

1) open emacs and project
1) M-x pipenv-activate
1) open file and run flycheck-verify-setup (to confirm that I'm pointed at pipenv's venv)
1) M-." or run "M-x company-diag"
1) message buffer displays "Symbol’s value as variable is void: pythonic-environment"

I also tried
1) open emacs and project
1) M-x pipenv-activate
1) open file and run flycheck-verify-setup (to confirm that I'm pointed at pipenv's venv)
1) run pythonic-activate and pass in the path to the pipenv venv 
    "/Users/ahonnecke/.local/share/virtualenvs/web-6EpGRwxA/"
1) M-." or run "M-x company-diag"
1) message buffer displays "Symbol’s value as variable is void: pythonic-environment"

**Comment by valignatev** [comment]
@ahonnecke 
@proofit404 Deleted `pythonic-environment` alltogether here: https://github.com/proofit404/pythonic/commit/3d5d79b811dfe33a65111d026fbc73145ead7524, so you're probably using an outdated version of `pythonic` package. Try to update it all and do it again :)

**Comment by ahonnecke** [comment]
That was absolutely it!  Thanks!
I'm now seeing the exact behavior you were expecting in https://github.com/proofit404/anaconda-mode/issues/293, which means that I'm waiting on https://github.com/davidhalter/jedi/issues/626; if I can help with testing anything, please let me know.  Thanks!
