### ISSUE TITLE
Cannot create ~/.emacs.d/anaconda-mode/0.1.11 directory

### ISSUE THREAD

**Issue by hnisonoff** [pythonic-emacs/anaconda-mode#294]
I am installing anaconda-mode as follows:
```
    (use-package anaconda-mode
      :ensure t
      :commands anaconda-mode
      :diminish anaconda-mode
      :init
      (progn
	(add-hook 'python-mode-hook 'anaconda-mode)
	(add-hook 'python-mode-hook 'eldoc-mode)))
```

When I try to use any mode-specific command I get the following error in *Messages*
`Cannot create ~/.emacs.d/anaconda-mode/0.1.11 directory`
Looking at *anaconda-mode* I see the following message:
Error executing Jupyter command '\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n': [Errno 2] No such file or directory

Any idea what is happening here? Thanks!

**Comment by proofit404** [comment]
Hi, Looks like a problem with concurrent access to the server, while it tries to bootstrap. Can you do following?
```lisp
M-: (anaconda-mode-stop) RET
;; don't touch anything few seconds
M-: (anaconda-mode-bootstrap) RET
;; wait again
```
Then try to use commands as usual with M-. and C-M-i.

**Comment by hnisonoff** [comment]
Thank you for the reply. 
Running `(anaconda-mode-stop)` return nil
Then after a few seconds, running `(anaconda-mode-bootstrap)` returned:
```
Debugger entered--Lisp error: (file-missing "Setting current directory" "No such file or directory" "/Users/hunternisonoff/.emacs.d/anaconda-mode/0.1.11")
  make-process(:name "anaconda-mode" :buffer #<buffer *anaconda-mode*> :command ("jupyter" "-c" "\nimport sys, site\nsys.path, remainder = sys.path[:1], sys.path[1:]\nsite.addsitedir('.')\nsys.path.extend(remainder)\nimport anaconda_mode\nanaconda_mode.main(sys.argv[-2:])\n" "127.0.0.1" ""))
  apply(make-process (:name "anaconda-mode" :buffer #<buffer *anaconda-mode*> :command ("jupyter" "-c" "\nimport sys, site\nsys.path, remainder = sys.path[:1], sys.path[1:]\nsite.addsitedir('.')\nsys.path.extend(remainder)\nimport anaconda_mode\nanaconda_mode.main(sys.argv[-2:])\n" "127.0.0.1" "")))
  start-process("anaconda-mode" #<buffer *anaconda-mode*> "jupyter" "-c" "\nimport sys, site\nsys.path, remainder = sys.path[:1], sys.path[1:]\nsite.addsitedir('.')\nsys.path.extend(remainder)\nimport anaconda_mode\nanaconda_mode.main(sys.argv[-2:])\n" "127.0.0.1" "")
  apply(start-process "anaconda-mode" #<buffer *anaconda-mode*> "jupyter" ("-c" "\nimport sys, site\nsys.path, remainder = sys.path[:1], sys.path[1:]\nsite.addsitedir('.')\nsys.path.extend(remainder)\nimport anaconda_mode\nanaconda_mode.main(sys.argv[-2:])\n" "127.0.0.1" ""))
  start-file-process("anaconda-mode" #<buffer *anaconda-mode*> "jupyter" "-c" "\nimport sys, site\nsys.path, remainder = sys.path[:1], sys.path[1:]\nsite.addsitedir('.')\nsys.path.extend(remainder)\nimport anaconda_mode\nanaconda_mode.main(sys.argv[-2:])\n" "127.0.0.1" "")
  apply(start-file-process "anaconda-mode" #<buffer *anaconda-mode*> "jupyter" ("-c" "\nimport sys, site\nsys.path, remainder = sys.path[:1], sys.path[1:]\nsite.addsitedir('.')\nsys.path.extend(remainder)\nimport anaconda_mode\nanaconda_mode.main(sys.argv[-2:])\n" "127.0.0.1" ""))
  start-pythonic(:process "anaconda-mode" :buffer "*anaconda-mode*" :cwd "~/.emacs.d/anaconda-mode/0.1.11" :filter #f(compiled-function (process output) #<bytecode 0x417edd09>) :sentinel anaconda-mode-bootstrap-sentinel :query-on-exit nil :args ("-c" "\nimport sys, site\nsys.path, remainder = sys.path[:1], sys.path[1:]\nsite.addsitedir('.')\nsys.path.extend(remainder)\nimport anaconda_mode\nanaconda_mode.main(sys.argv[-2:])\n" "127.0.0.1" ""))
  anaconda-mode-bootstrap()
  eval((anaconda-mode-bootstrap) nil)
  eval-expression((anaconda-mode-bootstrap) nil nil 127)
  funcall-interactively(eval-expression (anaconda-mode-bootstrap) nil nil 127)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```
Using the command C-M-i returned the same `Cannot create ~/.emacs.d/anaconda-mode/0.1.11 directory` error

**Comment by proofit404** [comment]
Do you see traceback in the `*anaconda-mode*` buffer?

**Comment by hnisonoff** [comment]
I see no traceback in the `*anaconda-mode*` buffer after running `(anaconda-mode-bootstrap)`. After trying C-M-i I get the following:
```
Error executing Jupyter command '\nimport os, sys\ndirectory = os.path.expanduser(sys.argv[-1])\nif not os.path.exists(directory):\n    os.makedirs(directory)\n': [Errno 2] No such file or directory
```

**Comment by proofit404** [comment]
Should be fixed in `0.1.12`.

**Comment by hnisonoff** [comment]
With the updated version I get the following error when using any of the commands.

> Error executing Jupyter command "\nfrom __future__ import print_function\n\n# CLI arguments.\n\nimport sys\n\nassert len(sys.argv) > 3, 'CLI arguments: %s' % sys.argv\n\nserver_directory = sys.argv[-3]\nserver_address = sys.argv[-2]\nvirtual_environment = sys.argv[-1]\n\n# Ensure directory.\n\nimport os\n\nserver_directory = os.path.expanduser(server_directory)\n\nif not os.path.exists(server_directory):\n    os.makedirs(server_directory)\n\n# Installation check.\n\ndef instrument_installation():\n    for path in os.listdir(server_directory):\n        path = os.path.join(server_directory, path)\n        if path.endswith('.egg') and os.path.isdir(path) and path not in sys.path:\n            sys.path.insert(0, path)\n\nmissing_dependencies = []\n\ninstrument_installation()\n\ntry:\n    import jedi\nexcept ImportError:\n    missing_dependencies.append('jedi>=0.12')\n\ntry:\n    import service_factory\nexcept ImportError:\n    missing_dependencies.append('service_factory>=0.1.5')\n\n# Installation.\n\nif missing_dependencies:\n    import site\n    import setuptools.command.easy_install\n    site.addsitedir(server_directory)\n    setuptools.command.easy_install.main([\n        '--install-dir', server_directory,\n        '--site-dirs', server_directory,\n        '--always-copy',\n        '--always-unzip',\n        *missing_dependencies\n    ])\n    instrument_installation()\n\n# Setup server.\n\nimport jedi\nimport service_factory\n\nassert jedi.__version__, 'Jedi version should be >= 0.12.0, current version: %s' % (\n    jedi.__version__,\n)\n\nif virtual_environment:\n    virtual_environment = jedi.create_environment(virtual_environment, safe=False)\nelse:\n    virtual_environment = None\n\n# Define JSON-RPC application.\n\nimport functools\n\ndef script_method(f):\n    @functools.wraps(f)\n    def wrapper(source, line, column, path):\n        return f(jedi.Script(source, line, column, path, environment=virtual_environment))\n    return wrapper\n\ndef process_definitions(f):\n    @functools.wraps(f)\n    def wrapper(script):\n        return [[definition.module_path,\n                 definition.line,\n                 definition.column,\n                 definition.get_line_code().strip()]\n                for definition in f(script)]\n    return wrapper\n\n@script_method\ndef complete(script):\n    return [[definition.name, definition.type]\n            for definition in script.completions()]\n\n@script_method\ndef company_complete(script):\n    return [[definition.name,\n             definition.type,\n             definition.docstring(),\n             definition.module_path,\n             definition.line]\n            for definition in script.completions()]\n\n@script_method\ndef show_doc(script):\n    return [[definition.module_name, definition.docstring()]\n            for definition in script.goto_definitions()]\n\n@script_method\n@process_definitions\ndef goto_definitions(script):\n    return script.goto_definitions()\n\n@script_method\n@process_definitions\ndef goto_assignments(script):\n    return script.goto_assignments()\n\n@script_method\n@process_definitions\ndef usages(script):\n    return script.usages()\n\n@script_method\ndef eldoc(script):\n    signatures = script.call_signatures()\n    if len(signatures) == 1:\n        signature = signatures[0]\n        return [signature.name,\n                signature.index,\n                [param.description[6:] for param in signature.params]]\n\n# Run.\n\napp = [complete, company_complete, show_doc, goto_definitions, goto_assignments, usages, eldoc]\n\nservice_factory.service_factory(app, server_address, 0, 'anaconda_mode port {port}')\n": [Errno 63] File name too long
> 
> Process anaconda-mode exited abnormally with code 1
>

**Comment by valignatev** [comment]
`ipython -c` works for me:
![image](https://user-images.githubusercontent.com/7038954/41199060-9ba4c700-6cce-11e8-8630-9d1ee556ca4d.png)

**Comment by proofit404** [comment]
The exactly same approach used in anaconda-mode. Looks like it can fail for some reason. Have no idea.

**Comment by valignatev** [comment]
Maybe Jupyter swallows empty strings as cli argument somehow? 
Like here: https://github.com/proofit404/anaconda-mode/blob/master/anaconda-mode.el#L325
Running this with ipython works consistently well for me. But in this particular case it looks like `anaconda-mode-server-command` is being tried to run with `jupyter` executable, not with ipython, hence the error.

@hnisonoff What emacs shows when you run `C-h v python-shell-interpreter`?
From [this](https://github.com/proofit404/anaconda-mode/issues/294#issuecomment-394010725) comment I could guess it would be `"jupyter"`
