### ISSUE TITLE
Possible workaround for jupyter console

### ISSUE THREAD

**Issue by et2010** [pythonic-emacs/anaconda-mode#304]
On windows, I have to use `jupyter console` as the interpreter or the matplotlib plot window [freezes](https://github.com/jorgenschaefer/elpy/issues/1041). But when I do so, the completion is gone. Is it possible to use `jupyter console` along with anaconda-mode? Thank you in advance!

This is what I use on windows:
```
(setq python-shell-interpreter "jupyter")
(setq python-shell-interpreter-args "console --simple-prompt")
```

I tried `jupyter-console` but that didn't work either.

**Comment by davidpham87** [comment]
Hello,

You can try to set 

```{elisp}
;; (setq python-shell-interpreter "ipython") ;; guess you should turn to 3 now :-)
(setq python-shell-interpreter "ipython3")
```
