### ISSUE TITLE
Tramp problem: Cannot read anaconda-mode server response

### ISSUE THREAD

**Issue by yolcu** [pythonic-emacs/anaconda-mode#311]
With the latest version of anaconda-mode from MELPA installed, whenever I am editing a remote file I get the error `Cannot read anaconda-mode server response` in the minibuffer.

`*anaconda-mode*` output:
```
anaconda_mode port 40778
```

`*anaconda-response*` output:
```
# status: (:error (error connection-failed deleted
 :host <remote_host> :service 40778) :error (error connection-failed failed with code 61
 :host <remote_host> :service 40778))
# point: 1

```

Everything works fine for local files and I have no extraordinary configuration done. Prior to updating everything worked fine even for remote files.

**Comment by valignatev** [comment]
It means that anaconda-mode can't reach server via 40778 port because it's closed most probably. Since you posted this issue there was one commit which should automatically local forward needed ports if you're working with ssh. Can you tell if it's still an issue with latest anaconda-mode?
