### ISSUE TITLE
Disable using TRAMP for completion

### ISSUE THREAD

**Issue by yolcu** [pythonic-emacs/anaconda-mode#321]
Is there a way to use local completions for a remote file? Whenever I am editing a file over TRAMP completion automatically tries to invoke a remote Python, and I would like to disable that if possible and simply use my local Python installation.

**Comment by proofit404** [comment]
Do not set up your python interpreter to the remote one.

**Comment by yolcu** [comment]
I have done 
    (setq-default python-shell-interpreter <local-path-to-python>)
but it still tries to use the remote one. Am I doing something wrong?

**Comment by proofit404** [comment]
Honestly, I have no idea.

**Comment by CeleritasCelery** [comment]
Does it work if you set `(defun pythonic-remote-p nil nil)`?
