### ISSUE TITLE
Completion doesn't work for methods of a variable

### ISSUE THREAD

**Issue by et2010** [pythonic-emacs/anaconda-mode#334]
After recent updates, completion for methods of a variable doesn't work.

This works:

![image](https://user-images.githubusercontent.com/11584902/46910780-678dad80-cf7d-11e8-80f7-a5cd2d63227a.png)

Sometimes, this works but takes a much longer time for the candidate list to pop up:

![image](https://user-images.githubusercontent.com/11584902/46910670-c43b9900-cf7a-11e8-843e-a67cacec1d08.png)

This never works - the candidate list never pops up:

![image](https://user-images.githubusercontent.com/11584902/46910686-f816be80-cf7a-11e8-94e6-538e74f44028.png)

In the last case, the echo area shows `Cannot read anaconda-mode server response' and there is a message in the anaconda-response buffer:

```
# status: (:error (error connection-failed deleted
 :host 127.0.0.1 :service 22125) :error (error connection-failed failed with code 10061
 :host 127.0.0.1 :service 22125))
# point: 1
```
It _does_ work before recent updates.

#### Environments

spacemacs with python layer enabled (on develop branch)

emacs 27.0.50

windows 8.1

python 3.6.5 (virtual environment)

**Comment by valignatev** [comment]
This works for me with latest anaconda-mode and plain emacs 26 (not spacemacs):
![image](https://user-images.githubusercontent.com/7038954/46911372-74e96e80-cf62-11e8-8984-4fd8d3b1659b.png)

It seems that you're using some kind of a remote setup, right?

**Comment by et2010** [comment]
> It seems that you're using some kind of a remote setup, right?

No, I'm not using a remote setup.

That's strange. A friend of mine has the exact issue. Maybe it's a spacemacs or python problem? I'll try to reproduce with another python 2.7 venv.

**Comment by proofit404** [comment]
Hi @et2010 

Please, try it without spacemacs on plain config.

**Comment by jkaye2012** [comment]
I'm on vanilla with company and anaconda. Everything was working for me until yesterday. Completion is completely broken for me only in anaconda-mode buffers. The inferior repl still completes properly and other modes are completing as well, which leads me to strongly suspect this is an issue in anaconda and neither company nor Jedi.

Please let me know what other information I can provide to aid in debugging!

**Comment by valignatev** [comment]
@jkaye2012 I would start the separate issue and post contents of *anaconda-mode* buffer there and maybe *Messages* buffer, because it might contain something related as well
