### ISSUE TITLE
No autocompletion on spacemacs (how to troubleshoot)?

### ISSUE THREAD

**Issue by dmitry-saritasa** [pythonic-emacs/anaconda-mode#339]
Hi Guys,

Read many related bugs and tickets and can't find anaconda mode to work. I get no autocompletion

Emacs-26.1
I'm using pyenv and virtual environment is activated inside emacs (pyenv-mode-set)
python 3.6.6
anaconda-mode      20181030.2109 installed 

```
CAPACITY_CLASSES = (
    Branch,
    Department,
    Worktype,
    Outsourcer,
    Employee,
)

CAPACITY_CLASSES.Br
```

I'm expecting Branch to be autocompleted, but nothing happens when I invoke C-M-i (anaconda-mode-complete)

Dmitry

**Comment by dakra** [comment]
@dmitry-saritasa does the completion work anywhere else?

That it doesn't find a completion for `CAPACITY_CLASSES.Br`
is correct because there is no completion for it.
In Python you access a Tuple element by number so e.g.
`CAPACITY_CLASSES[0]`.

**Comment by wizmer** [comment]
Recently I also had an issue with spacemacs and anaconda on spacemacs develop branch that I solved by modifying the content of anaconda-mode.el to a more recent version.
Can you post the content of your *anaconda-mode* buffer ?
