### ISSUE TITLE
Completion for dataclasses

### ISSUE THREAD

**Issue by quicknir** [pythonic-emacs/anaconda-mode#361]
This could be another issue in my setup, but I can't seem to get completion for dataclasses to work.

```
from dataclasses import dataclass

@dataclass
class Student:
    name: str
    id_num: int


class User:
    def __init__(self, name, id_num):
        self.name = name
        self.id_num = id_num

def foo(s: Student, u: User):
    pass
    # I get completion on u. but not on s.
```

**Comment by CeleritasCelery** [comment]
I am not able to reproduce this. Using your same example I get completions for `s`. Version 0.15.0 of Jedi added support for dataclasses. Which version are you using?

**Comment by CeleritasCelery** [comment]
Actually is looks like that version of Jedi was released after you filed you issue. Please Update and test again.
