### ISSUE TITLE
Error installing package using easy_install in Windows

### ISSUE THREAD

**Issue by xx299x** [pythonic-emacs/anaconda-mode#362]
![image](https://user-images.githubusercontent.com/23482348/62634784-0ea66000-b969-11e9-9bfa-b23f2b5ba895.png)

`unknow url type: https....`

My solution is to modify CMD in anaconda-mode.el.
Add the following code `--index-url=http://mirrors.aliyun.com/pypi/simple/` at the end of the list of cmd.

![image](https://user-images.githubusercontent.com/23482348/62635364-1d414700-b96a-11e9-84fd-bcaefd39fae0.png)

Finally, please forgive my poor English

**Comment by CeleritasCelery** [comment]
So if you change the url to use http, then easy_install works?

**Comment by xx299x** [comment]
> So if you change the url to use http, then easy_install works?

Yes, it works very well.

**Comment by CeleritasCelery** [comment]
Are you behind a proxy? I very surprised that it cannot recognize https

**Comment by xx299x** [comment]
> I am very surprised that it cannot recognize https as a valid url. Since you have found a workaround, and I don’t see this issue with windows install, I think the best course will be to close this issue. I don’t want to change default url used by easy_install.

OK
