### ISSUE TITLE
Problems with installing on Emacs 25

### ISSUE THREAD

**Issue by brtsay** [pythonic-emacs/anaconda-mode#367]
Hi,
After #364 which introduced posframe as a dependency, I can no longer install anaconda-mode via `list-packages` from MELPA. 
![image](https://user-images.githubusercontent.com/6187530/65084327-e69f1900-d978-11e9-8693-96627b82319e.png)
I believe the issue is that the versions of posframe on GNU and MELPA all require Emacs 26. I am using

- Emacs 25.2.2 (installed via apt on Ubuntu)
- Ubuntu 18.04

**Comment by CeleritasCelery** [comment]
I think the best course of action here is to remove it from the `package-requires` and add a check when we try to use it to see if the package is a available. Unfortunately, this will mean that posframe  is not downloaded automatically when the package is installed, but I don’t see another option.
