### ISSUE TITLE
[question] some warnings upon installation

### ISSUE THREAD

**Issue by kirk86** [pythonic-emacs/anaconda-mode#370]
Upon installation I received the following warnings
```
warning (bytecomp): the following functions are not known to be defined:
    posframe-workable-p, posframe-show, posframe-hide, -const
````
Is that normal behaviour?

**Comment by dakra** [comment]
Thanks for reporting. Those warnings are harmless as the functions will only be called when you have the `posframe` package installed and the anaconda option for it set.
I pushed a fix anyway to remove the warnings.
