### ISSUE TITLE
[question] is pythonic absolutely necessary

### ISSUE THREAD

**Issue by kirk86** [pythonic-emacs/anaconda-mode#372]
I was wondering if `pythonic` is absolutely necessary, maybe it would be better to allow the users to decide which virtualenv package they want to have installed in their systems. If a user preferes another virtualenv package then they'll have to end up with 2 different packages for the same purpose. Is `anaconda-mode` using `pythonic` in some sense that cannot be modularised?

**Comment by dakra** [comment]
Do you mean [this pythonic](https://github.com/pythonic-emacs/pythonic)?

If so, it's not really a package to handle your virtualenvs.
It has a very simple helper command to set the
`python-shell-virtualenv-path` but that's about it.

It's main purpose is to conveniently call your currently active
venv python process and work with it from elisp.

**Comment by kirk86** [comment]
@dakra Got it, thanks for clarifying my confusion...
