### ISSUE TITLE
anaconda-mode-find-definitions-other-window fails after upgrading to emacs 26.3

### ISSUE THREAD

**Issue by triccare** [pythonic-emacs/anaconda-mode#374]
Greetings,

Recently upgraded Emacs, using emacsforosx, from 26.2 to 26.3. Now, when attempting to use `anaconda-mode-find-definitions-other-window`, the following error occurs:

`error in process filter: Wrong type of argument: listp, window`

Environment: MAC OS 10.13.6, Emacs 26.3 (emacsforosx), spacemacs (develop), python-mode

I am lisp-aware but not proficient. Will attempt further debugging if time permits. As such, pointers to where to start would be useful.

**Comment by CeleritasCelery** [comment]
Thanks for the report! Please verify the fix works for you.

**Comment by triccare** [comment]
👍 Success! Thank you for your time.
