### ISSUE TITLE
Anaconda-mode does not work in tramp

### ISSUE THREAD

**Issue by theFool32** [pythonic-emacs/anaconda-mode#377]
Anaconda-model works locally. When used in tramp, it can't work, and the `anaconda-mode` looks like:
```
Traceback (most recent call last):
  File "<string>", line 60, in <module>
  File "<string>", line 50, in install_deps
ModuleNotFoundError: No module named 'setuptools'
```

I'm using mac ox locally and linux remotely, where `setuptools` has been installed both.
I don't know how to deal with it.
Configure for Emacs is doom-emacs with 
```
(python
+lsp
+conda)
```

Thanks. 😃

**Comment by CeleritasCelery** [comment]
It looks like the python module `setup_tools` is not installed on the remote host.

**Comment by theFool32** [comment]
It seems that the `miniconda` installed on the remote host conflicts.
Thanks.
