### ISSUE TITLE
service_factory removed from PyPi preventing anaconda-mode server from running

### ISSUE THREAD

**Issue by AloisJanicek** [pythonic-emacs/anaconda-mode#384]
https://pypi.org/project/service_factory/ results in `404`

`pip search service_factory `returns nothing

Author apparently deleted package from PyPi and [is asking colleges](https://github.com/pythonic-emacs/service-factory/issues/2) to re-publish it.

I managed `anaconda-mode` to get properly working by installing `service_factory` python package locally:
```
git clone https://github.com/pythonic-emacs/service-factory.git
sudo pip install -e service_factory
```
and deleting line [129](https://github.com/pythonic-emacs/anaconda-mode/blob/master/anaconda-mode.el#L129) in `anaconda-mode.el`

**Comment by CeleritasCelery** [comment]
service_factory is republished.
