### ISSUE TITLE
codecomplete donnot work in my project

### ISSUE THREAD

**Issue by zcjava** [pythonic-emacs/anaconda-mode#389]
anaconda can code-complete python dependencies. but in my project. it donnot code-complete my def function in other python file

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/85284940-97b38080-b4c2-11ea-90d7-6c7b46d26883.png)

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/85285008-b6197c00-b4c2-11ea-965f-81e7749fd20b.png)

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/85285029-c2053e00-b4c2-11ea-8633-4cb85998cfd9.png)

**Comment by zcjava** [comment]
b. not working

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/85285348-5a032780-b4c3-11ea-93dd-a3dc48feb213.png)

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/85285379-6be4ca80-b4c3-11ea-94fe-bc8723e73d9d.png)

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/85285421-7d2dd700-b4c3-11ea-966b-98320aeb0ad3.png)

**Comment by zcjava** [comment]
b. not work

**Comment by zcjava** [comment]
![image](https://user-images.githubusercontent.com/1551382/85285758-0c3aef00-b4c4-11ea-825a-70d336d23e05.png)

**Comment by dakra** [comment]
What's the value of `company-minimum-prefix-length`?
By default that's 3 which means only after 3 characters you get a company completion.

**Comment by zcjava** [comment]
> What's the value of `company-minimum-prefix-length`?
> By default that's 3 which means only after 3 characters you get a company completion.

![image](https://user-images.githubusercontent.com/1551382/85296699-604dcf80-b4d4-11ea-8074-278bdf05270b.png)

2 or 3 word not work.  dot Symbol toggle company-anaconde , but not work.   i use class of python dependencies package  is work .  Not for this reason

**Comment by zcjava** [comment]
use company-complete , it tips : don not match.
*anaconda-mode* buffer  is not problem.  anaconda-mode is work. see above images . logging class is work.  but my project class not work

**Comment by dakra** [comment]
Hmm. Are `a.py` and `b.py` really in a proper python package? I.e. is there a `__init__.py` file in the same folder?
Otherwise I'm out of guesses ;)

**Comment by zcjava** [comment]
yes . same project same package . i sure.

**Comment by zcjava** [comment]
u see above image about from . import b.  i use flycheck . is not error. compiler correct

**Comment by zcjava** [comment]
> Hmm. Are `a.py` and `b.py` really in a proper python package? I.e. is there a `__init__.py` file in the same folder?
> Otherwise I'm out of guesses ;)

but thanks

**Comment by dakra** [comment]
Flycheck has multiple backends. what checker is active?

Just to make double sure.
In your directory are:
```
__init__.py
a.py
b.py
```

Because it really looks like it isn't with all you described so far.

**Comment by zcjava** [comment]
> Flycheck has multiple backends. what checker is active?
> 
> Just to make double sure.
> In your directory are:
> 
> ```
> __init__.py
> a.py
> b.py
> ```
> 
> Because it really looks like it isn't with all you described so far.

i use scrapy shell create projecte .   director must be corrent. because  my home pc same project and same spacemacs properties can work . but my work pc not work . i berserk.

**Comment by zcjava** [comment]
> Flycheck has multiple backends. what checker is active?
> 
> Just to make double sure.
> In your directory are:
> 
> ```
> __init__.py
> a.py
> b.py
> ```
> 
> Because it really looks like it isn't with all you described so far.

flycheck is active . see above image about major mode list .
director list :
    ├── BillFlow.py
    ├── BizUtil.py
    ├── CorpYearBill.py
    ├── PersonYearBill.py
    ├── TeamYearBill.py
    ├── Utils.py
    ├── __init__.py
    ├── a.py
    ├── b.py
    └── org

**Comment by dakra** [comment]
This is strange.
Did you say it works on one PC and not on another?
Some OS, same Python etc?

**Comment by zcjava** [comment]
> This is strange.
> Did you say it works on one PC and not on another?
> Some OS, same Python etc?

yes. same os(mac os ) , same py(python3.7.7), same spacemacs setting, same project . is very strage.

**Comment by zcjava** [comment]
> Flycheck has multiple backends. what checker is active?
> 
> Just to make double sure.
> In your directory are:
> 
> ```
> __init__.py
> a.py
> b.py
> ```
> 
> Because it really looks like it isn't with all you described so far.

OMG! i get reason. u are right. i import module error . anaconda is corrent

**Comment by dakra** [comment]
Nice. I think we can close this issue then?

I think the pycompile checker just checks if the syntax is correct. It's doesn't actually run the import and look if that module is actually there while jedi actually does the import for the completion (which then failed).

**Comment by zcjava** [comment]
> Nice. I think we can close this issue then?
> 
> I think the pycompile checker just checks if the syntax is correct. It's doesn't actually run the import and look if that module is actually there while jedi actually does the import for the completion (which then failed).

u are right . same project code and same python env and same spacemacs settings in two pc machine . i donnot know why import module incorrect in one pc and corrrent in other one pc.  but actually just import module problem.
