### ISSUE TITLE
Symbol’s function definition is void: pythonic-local-p

### ISSUE THREAD

**Issue by etam** [pythonic-emacs/anaconda-mode#408]
Installed from melpa stable:
- anaconda: 0.1.14
- pythonic: 0.1.1

```
anaconda-mode-get-server-process-cwd: Symbol’s function definition is void: pythonic-local-p
```

The variable `pythonic-local-p` is defined in pythonic git, but not in latest stable release.

**Comment by dakra** [comment]
Sorry. I just released a new version of `pythonic`. Should hit melpa stable soon.

**Comment by etam** [comment]
That was fast! Thanks. It works now.
