### ISSUE TITLE
[FR] Add option to disable anaconda-mode's RPC calls completely when on TRAMP

### ISSUE THREAD

**Issue by NightMachinery** [pythonic-emacs/anaconda-mode#413]
anaconda-mode's RPC calls completely break my TRAMP python files, as there are lots of slow RPC calls. I have for now completely disabled anaconda-mode, but I would like to just disable it for TRAMP buffers. Thanks!

**Comment by falloutphil** [comment]
My guess from inspecting the code is that we need a new `defcustom` called `anaconda-mode-disable-rpc` which should have 3 states - never, remote, always

Then here:
https://github.com/pythonic-emacs/anaconda-mode/blob/344727c9e07e108896740c782689bf3588edcce5/anaconda-mode.el#L358

We need to test the new custom variable and in combination with `pythonic-remote-p` we can decide whether to proceed with the call or not.

If my guess id right it's probably a simple fix.  If I get time over the next few weeks I will try to look at this if nobody else implements first.

Shout if you think I'm missing the point and I'll refine this.
